version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: TomKalina-changedetection.io_1
      APP_PORT: 4546
    
  server:
    image: dgtlmoon/changedetection.io:latest
    user: "4546:80"
    init: true
