version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: lerix-changedetection.io_1
      APP_PORT: 5000
    
  server:
    image: dgtlmoon/changedetection.io:latest
    user: "5000:5000"
    init: true
    restart: on-failure
    volumes:
      - "${APP_DATA_DIR}/datastore:/datastore"
